name: Check Markdown links

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5.0.0
    - uses: gaurav-nelson/github-action-markdown-link-check@1.0.17
